# Generated by Django 2.2.6 on 2019-10-17 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['apellido', 'Primer_nombre']},
        ),
        migrations.RenameField(
            model_name='anim',
            old_name='author',
            new_name='Creador',
        ),
        migrations.RenameField(
            model_name='anim',
            old_name='Summary',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='anim',
            old_name='title',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='date_of_birth',
            new_name='Nacimiento',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='first_name',
            new_name='Primer_nombre',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='last_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='TipoGenero',
        ),
        migrations.RemoveField(
            model_name='author',
            name='date_of_death',
        ),
    ]
